Repository 30-seconds/30-seconds-of-python, pull requests merged in 2020-01, with the labels that each got.

#172 Add function snippets
  snippets/check_prop.md
  snippets/compose.md
  snippets/compose_right.md
  snippets/curry.md
  snippets/delay.md
  snippets/unfold.md
  snippets/when.md
Labels: enhancement, not-stale

#173 Fix snippet problems
  snippets/all_equal.md
  snippets/all_unique.md
  snippets/bifurcate.md
  snippets/bifurcate_by.md
  snippets/camel.md
  snippets/cast_list.md
  snippets/check_prop.md
  snippets/chunk.md
  snippets/clamp_number.md
  snippets/compose.md
  snippets/compose_right.md
  snippets/curry.md
  snippets/deep_flatten.md
  snippets/degrees_to_rads.md
  snippets/delay.md
  snippets/difference_by.md
  snippets/digitize.md
  snippets/every_nth.md
  snippets/factorial.md
  snippets/fibonacci.md
  snippets/gcd.md
  snippets/group_by.md
  snippets/has_duplicates.md
  snippets/head.md
  snippets/in_range.md
  snippets/initial.md
  snippets/initialize_list_with_range.md
  snippets/is_anagram.md
  snippets/kebab.md
  snippets/lcm.md
  snippets/longest_item.md
  snippets/max_by.md
  snippets/min_by.md
  snippets/most_frequent.md
  snippets/n_times_string.md
  snippets/rads_to_degrees.md
  snippets/reverse_string.md
  snippets/sample.md
  snippets/shuffle.md
  snippets/snake.md
  snippets/spread.md
  snippets/sum_by.md
  snippets/tail.md
  snippets/transpose.md
  snippets/union.md
  snippets/union_by.md
  snippets/zip.md
Labels: bug, enhancement

#180 Fix Counter typo
  snippets/filter_non_unique.md
  snippets/filter_unique.md
Labels: enhancement

#179 Add find_parity_outliers
  snippets/find_parity_outliers.md
Labels: enhancement

#182 [FIX] Typo in snake snippet
  snippets/snake.md
Labels: bug

#183 [FIX] Typo in max-element-index snippet
  snippets/max_element_index.md
Labels: bug
